import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import GlobalFooter from '@/components/layout/footer';
import GlobalHeader from '@/components/layout/header';
import '../globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'East Bro',
	description: 'Generated by East Bro',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<GlobalHeader />
				<main>{children}</main>
				<GlobalFooter />
			</body>
		</html>
	);
}
